version: "3.7"

services:
  api-server:
    build:
      context: ../
      dockerfile: docker/back-end/Dockerfile
    ports:
      - "5000:5000"

  mongo:
    image: "mongo:4.2"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
